config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "pages#home"

  resources :sharks do
    resources :bookings, only: [:new, :create, :show]
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :index]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :shark
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shark
  belongs_to :user
  ratings = (0..5)

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  validates :rating, presence: true, inclusion: { in: ratings }, numericality: { only_integer: true }
end

app/models/shark.rb
class Shark < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_many :reviews, dependent: :destroy

  validates_presence_of :name, :age, :breed, :description, :price, :diet, :picture_url
  validates :age, numericality: { only_integer: true }
  validates :price, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :sharks
  has_many :bookings
  has_many :sharks, through: :bookings
  has_many :reviews

  validates_presence_of :first_name, :last_name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_shark, only: [:new, :create]
  before_action :set_booking, only: [:destroy]

  def index
    @user_id = current_user.id
    @bookings = Booking.where(user_id: @user_id)
    @sharks = Shark.where(user_id: @user_id)
  end

  def new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.shark = @shark
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path
    else
      render 'bookings/new', status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to sharks_path, status: see_other
  end

  private

  def set_shark
    @shark = Shark.find(params[:shark_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_shark, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.shark = @shark
    @review.user = current_user
    if @review.save
      redirect_to shark_path(@shark)
    else
      # render :new, status: :unprocessable_entity
      flash.alert = "Review can't be saved. Please enter information."
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to shark_path(@review.shark), status: :see_other
  end

  private

  def set_shark
    @shark = Shark.find(params[:shark_id])
  end

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/controllers/sharks_controller.rb
class SharksController < ApplicationController
  before_action :set_shark, only: [:edit, :show, :update, :destroy]

  def index
    @sharks = Shark.all
  end

  def show
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @shark = Shark.new
  end

  def create
    @shark = Shark.new(shark_params)
    @shark.user = current_user
    # raise
    if @shark.save!
      redirect_to shark_path(@shark)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @shark.update(shark_params)
      redirect_to shark_path(@shark)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @shark.destroy
    redirect_to sharks_path, status: :see_other
  end

  private

  def set_shark
    @shark = Shark.find(params[:id])
  end

  def shark_params
    params.require(:shark).permit(:name, :age, :breed, :description, :price, :diet, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@shark, @booking] do |f| %>
  <%= f.input :start_date, html5: true, :label_html => { :class => 'text-white' } %>
  <%= f.input :end_date, html5: true, :label_html => { :class => 'text-white' } %>
  <%= f.submit 'Book Shark', data: { confirm: "Confirm" }, class: "btn-big" %>
<% end %>

app/views/bookings/index.html.erb
<div class="card-homepage">
    <h2>Your Bookings</h2>
  <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="card-shark">
          <%= link_to shark_path(booking.shark) do %>
            <img src="<%= booking.shark.picture_url%>" alt="">
          <% end %>
          <div class="card-shark-info">
            <div class="card-flex-content">
              <h3 class="dark-text"><strong><%= booking.shark.name %></strong></h3>
              <h4 class="booking-text">£<%= booking.shark.price %> x <%= pluralize (booking.end_date - booking.start_date).to_i, "day" %> <br>Total: £<%= (booking.shark.price * (booking.end_date - booking.start_date)).to_i %></h4>
              <p class="booking-text">From: <%=booking.start_date.strftime("%b %d, %Y")%><br>To: <%=booking.end_date.strftime("%b %d, %Y")%></p>
            </div>
            <%= link_to "See shark", shark_path(booking.shark), class: "btn-big" %>
          </div>
        </div>
      <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SharkBait</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="shortcut icon" href="shark.ico"/>
<!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Climate+Crisis&family=League+Spartan:wght@400;500;600&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
  </head>

  <body>
  <div class="wrapper">
    <%= render "shared/navbar" %>
    <div class="container-pages">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <div class="push"></div>
  </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_home_cards.html.erb
<div class="homepage-cards-container">
      <div class="homepage-card">
          <div class="face face1">
              <div class="home-card-content">
                  <i class="fa-solid fa-fish"></i>
                  <h3>Rent A Shark</h3>
              </div>
          </div>
          <div class="face face2">
              <div class="home-card-content">
                  <p>We've got sharks for all the family. Big ones, small ones, playful ones & even hungry ones!</p>
                  <a href="/sharks" class="btn-big">See our sharks</a>
              </div>
          </div>
      </div>
      <div class="homepage-card">
          <div class="face face1">
              <div class="home-card-content">
                  <i class="fa-solid fa-water"></i>
                  <h3>List Your Shark With Us</h3>
              </div>
          </div>
          <div class="face face2">
              <div class="home-card-content">
                  <p>We are the only place online to rent out your shark, so you have no other choice!</p>
                  <a href="/sharks/new" class="btn-big">List a shark</a>
              </div>
          </div>
      </div>
      <div class="homepage-card">
          <div class="face face1">
              <div class="home-card-content">
                  <i class="fa-solid fa-disease"></i>
                  <h3>#1 Shark Rental Service</h3>
              </div>
          </div>
          <div class="face face2">
              <div class="home-card-content">
                  <p>By shark-lovers, for shark-lovers. We believe they get a bad rap! Discover our story.</p>
                  <a href="/sharks" class="btn-big">About</a>
              </div>
          </div>
      </div>
  </div>

app/views/pages/home.html.erb
<div class="container-home">
  <div class="card-homepage">
    <div class=" d-flex flex-column align-items-center">
      <h1 id="company_name">SharkBa<span class="red-text">i</span>t</h1>
      <h3 class="white-text">Your #1 reef-source for everything sharks</h3>
      <br>
        <%# <h2 id="tagline">I chews you</h2> %>
          <%= image_tag "shark_vector.png", alt: "shark cartoon" %>
        <br>
    </div>
    <div class=" d-flex flex-column">
      <%= render 'home_cards' %>
    </div>
  </div>
</div>

      <%# <p>Ever felt like your life was hollow and needed a little bite?</p>
      <p>Are you allergic to cats but always wanted a pet?</p>
      <p>Did you ever think dog-ownership was for self-hating suckers?</p>
        <br> %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@shark, @review] do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn-big" %>
<% end %>

app/views/reviews/_modal_form.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/reviews/new.html.erb
<div class="card-background">
  <%= link_to sharks_path do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <h2>Write a Review</h2>
  <%= render 'reviews/form' %>
</div>

app/views/shared/_button.html.erb
<a href="" class="btn-big">Hello! Click Me</a>

app/views/shared/_footer.html.erb
<div class="footer">
    <div class="col">
      <p><%= link_to "c 2023 SharkBait, Inc. All rights reserved." %></p>
    </div>
    <div class="col">
      <p><%= link_to "Designed by: Ben, Malak, Linnea, Luke & Camille" %></p>
    </div>
    <div class="col">
      <div class="icons-col">
        <a href="#"><i class="fa-brands fa-facebook rounded p-1"></i></a>
        <a href="#"><i class="fa-brands fa-twitter rounded p-1"></i></a>
        <a href="#"><i class="fa-brands fa-pinterest rounded p-1"></i></a>
        <a href="#"><i class="fa-brands fa-linkedin rounded p-1"></i></a>
        <a href="#"><i class="fa-brands fa-instagram rounded p-1"></i></a>
        <a href="#"><i class="fa-brands fa-youtube rounded p-1"></i></a>
      </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon nav-height">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1 class="white-text" id="company_name">SharkBa<span class="red-text">i</span>t</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>



    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "List a shark", new_shark_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "See all sharks", sharks_path , class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "Avatar_Photo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Homepage", root_path , class: "dropdown-item" %>
              <%= link_to "Browse sharks", sharks_path, class: "dropdown-item" %>
              <%= link_to "Add a new shark", new_shark_path , class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/sharks/_form.html.erb
<%= simple_form_for @shark do |f| %>
  <%= f.input :name, :label_html => { :class => 'text-white' } %>
  <%= f.input :age, :label_html => { :class => 'text-white' } %>
  <%= f.input :breed, :label_html => { :class => 'text-white' } %>
  <%= f.input :description, :label_html => { :class => 'text-white' } %>
  <%= f.input :price, :label_html => { :class => 'text-white' } %>
  <%= f.input :diet, :label_html => { :class => 'text-white' } %>
  <%= f.input :picture_url, :label_html => { :class => 'text-white' } %>
  <%= f.button :submit, class: "btn-big"%>
<% end %>

<%# :name, :age, :type, :description, :price, :diet, :picture_url %>

app/views/sharks/edit.html.erb
<div class="card-background">
  <div class="icon-title">
    <%= link_to sharks_path do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
  <h2>Edit a Shark</h2>
  </div>
  <%= render 'sharks/form' %>
</div>

app/views/sharks/index.html.erb
<div class="card-homepage">
  <h2>Our Sharks</h2>
  <div class="cards">
    <% @sharks.each do |shark| %>
      <div class="card-shark">
        <%= link_to shark_path(shark) do %>
          <img src="<%= shark.picture_url%>" alt="">
        <% end %>
        <div class="card-shark-info">
          <div class="card-flex-content">
            <h3 class="dark-text"><strong><%= shark.name %></strong></h3>
            <h4 class="dark-text">£<%= shark.price %></h4>
          </div>
          <%= link_to "See more", shark_path(shark), class: "btn-big" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/sharks/new.html.erb
<div class="card-background">
  <div class="icon-title">
    <%= link_to sharks_path do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
  <h2>List a Shark</h2>
  </div>
  <%= render 'sharks/form' %>
</div>

app/views/sharks/show.html.erb
<div class="show-shark">
  <div class="shark-title">
    <div class="showpage-icons">
        <%= link_to sharks_path do %>
        <i class="fa-solid fa-arrow-left"></i>
        <% end %>

      <% if @shark.user == current_user %>
        <div class="edit-delete-icons">
        <%= link_to edit_shark_path do %>
        <i class="fas fa-edit"></i>
        <% end %>

        <%= link_to shark_path(@shark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash-can"></i>
        <% end %>

    <% else %>
      <%= link_to sharks_path do %>
          <i class="fa-solid fa-arrow-left" style="display:none"></i>
        <% end %>

        <div class="edit-delete-icons" style="display:none">
          <%= link_to edit_shark_path do %>
            <i class="fas fa-edit" style="display:none"></i>
          <% end %>

        <%= link_to shark_path(@shark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-solid fa-trash-can" style="display:none"></i>
        <% end %>
      </div>
    <% end %>
    </div>
  </div>
    <h2><%= @shark.name %></h2>
  <div class="image-details-flex">
    <img src="<%= @shark.picture_url%>" alt="shark image">
    <div class="shark-details">
      <p><strong>Age: </strong><%= @shark.age %></p>
      <p><strong>Shark Breed: </strong><%= @shark.breed %></p>
      <p><strong>Diet: </strong><%= @shark.diet %></p>
      <p><strong>Price:</strong> £<%= @shark.price %>/day</p>
    </div>
  </div>
  <br>
  <div class="details-flex">
    <div class="shark-description">
    <div class="title-icons">
      <h3>About <%= @shark.name %></h3>
      </div>
      <br>
      <p>
        <%= @shark.description %>
      </p>
    </div>
    <div class="embed-booking">
      <h3>Book <%= @shark.name %></h3>
      <br>
      <%= render 'bookings/form' %>
    </div>
  </div>
    <br>
    <div class="embed-review-form">
      <h2>Reviews</h2>

    <div class="list-reviews-flex">
      <% if @shark.reviews.blank? %>
        <p id="text-no-reviews">No'fin here yet! Be the first to leave a review for </p> &nbsp;<%= @shark.name %>.
      <% else %>
          <% @shark.reviews.each do |review| %>
            <div class="list-review-detail">
              <h5><%= review.title %>&nbsp;&nbsp;<%= '⭐️' * review.rating %></h5>
              <p><%= review.content %></p>
             <!-- <p>Rating: <%= review.rating %></p> -->
              <p><em>- <%=review.user.first_name%> <%=review.user.last_name%></em></p>
            <% if review.user == current_user %>
              <%= link_to review_path(review), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <br>
    <%= link_to "Leave a review", new_shark_review_path(@shark), class: "btn-big" %>
    <br>
    </div>
</div>